# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://cw.evg-soft.com
title: Evgsoft - Courseware development 
email: email@evg-soft.com
author: Evgsoft
description: > # "Write an awesome description for your new site here. 
 We are a company that specializes in developing curricula and courseware for information technologies and products. 
 Our experience over the past year, we developed an original curriculum of courses, including: 
copyright: 'Copyright &copy; 2017 Evgsoft. All Rights Reserved.'
#credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  #- title: twitter
  #  url: https://twitter.com/
#  - title: github
 #   url: https://github.com/
#  - title: linkedin
#    url: www.linkedin.com/in/eugenebelous
  - title: telegram
    url: https://t.me/courseware_development
  - title: question
    url: mailto:email@evg-soft.com
 

